steps:
  # イメージをビルド
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "$_CONTAINER_REGISTRY/$_IMAGE_NAME:$SHORT_SHA"
      - .
  # Container RegistryにPush
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "$_CONTAINER_REGISTRY/$_IMAGE_NAME:$SHORT_SHA"
  # Cloud Runサービスにデプロイする
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - $_CLOUD_RUN_SERVICE_NAME
      - "--image=$_CONTAINER_REGISTRY/$_IMAGE_NAME:$SHORT_SHA"
      - "--port"
      # コンテナの公開ポートをここで指定する
      - "80"
      - "--region"
      - $_REGION
images:
  - "$_CONTAINER_REGISTRY/$_IMAGE_NAME:$SHORT_SHA"
options:
  logging: CLOUD_LOGGING_ONLY
